<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\Interfaces\" />
    <Folder Include="Domain\Services\" />
    <Folder Include="Infrastructure\ExternalServices\Models\" />
    <Folder Include="Infrastructure\Persistence\Migrations\" />
    <Folder Include="Infrastructure\Persistence\Repositories\" />
    <Folder Include="Worker\" />
  </ItemGroup>

</Project>
